imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

swiftmailer:
    transport: gmail
    #host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    #auth_mode: "%mailer_auth_mode%"
    #port:      "%port%"
    #encryption: "%mailer_encryption%"
#    delivery_address: me@example.com
